### ISSUE TITLE
404 error on every request. 

### ISSUE THREAD

**Issue by Saroufim** [flathub/edu.stanford.Almond#1]
Almod yields a 404 error on any form of input including the replies to the startup tutorial.

**Comment by gcampax** [comment]
Thank for your report, that's definitely unexpected.
To start debugging, can I ask you what locale you're using? (the exact value of $LANG and similar $LC_ variables)

Thanks!

**Comment by Saroufim** [comment]
$LANG = es_ES.UTF-8 
$LC_DATE and $LC_ALL echo nothing. As you may guess, my desktop's local is Spain Spanish and the keyboard in use is English (US) on a fully updated Fedora 28. The desktop environment is GNOME. I hope this helps

**Comment by gcampax** [comment]
Thanks again, I found a misconfiguration on our backend server. It should be fixed now. Can you confirm?
Please note by the way that Almond is at the moment only working in English, and it will expect commands in English.

**Comment by Saroufim** [comment]
It works now, thank you! I realize it supports English only and I realize the project is incomplete and doesn't match other more commercial alternatives yet. Good luck with bringing it further!
